<?php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
// Passed variables: $atts (array from shortcode)

$list_args = [
    'taxonomy'     => ESC_Taxonomy::TAXONOMY_NAME,
    'orderby'      => $atts['orderby'] ?? 'name',
    'order'        => $atts['order'] ?? 'ASC',
    'show_count'   => $atts['show_count'] ?? false, // Note: Count won't reflect custom table easily without extra work
    'hierarchical' => $atts['hierarchical'] ?? true,
    'title_li'     => $atts['title_li'] ?? '', // No wrapping <li> title by default
    'echo'         => false, // Return the list HTML
    'hide_empty'   => false, // Show categories even if no seeds are linked (yet)
];

$category_list_html = wp_list_categories( $list_args );

// Optional: Add data-term-id for AJAX filtering
if ($atts['hierarchical']) { // Only practical for hierarchical lists
    $category_list_html = preg_replace_callback(
        '/<a href="([^"]+)"\s*data-term-id="(\d+)"/', // Add placeholder attribute if modifying later
        function($matches) {
            // Try to extract term ID from the URL if possible (more complex)
            // Or, easier, modify wp_list_categories walker or filter 'wp_list_categories'
            // For now, we'll rely on JS adding it if needed or modifying the link href logic in JS
            return '<a href="'. $matches[1] .'" data-term-id="">'; // Placeholder
        },
        $category_list_html
    );
     // Simpler approach: Modify links in JS based on href if needed.
     // Or pass term data to JS via wp_localize_script if generating list manually.
}


?>
<div id="esc-categories-container" class="esc-container">
    <?php if ( ! empty( $category_list_html ) ) : ?>
        <h2><?php esc_html_e( 'Seed Categories', 'erins-seed-catalog' ); ?></h2>
        <ul class="esc-category-list">
            <?php echo $category_list_html; // Output the list generated by wp_list_categories ?>
        </ul>
    <?php else : ?>
        <p><?php esc_html_e( 'No seed categories found.', 'erins-seed-catalog' ); ?></p>
    <?php endif; ?>
</div>